#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xset r rate 250 60 &
numlockx on &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         	0
bspc config window_gap          	2

bspc config split_ratio			0.45
bspc config borderless_monocle		false
bspc config gapless_monocle		false
bspc config single_monocle		true
bspc config focus_follows_pointer	true

bspc config top_padding			3
bspc config bottom_padding		3
bspc config left_padding		3
bspc config right_padding		3

bspc config pointer_modifier		mod4
bspc config pointer_action1		move
bspc config pointer_action2		resize_side
bspc config pointer_action3		resize_corner

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on 
bspc rule -a xcalc state=floating sticky=on center=true
bspc rule -a Gpick state=floating sticky=on rectangle=515x460+1012+10
